paths:
  /realestate/building/by-fullname:
    get:
      operationId: getBuildingTitleByFullname
      summary: 건축물대장 표제부 (풀네임+번지→PNU, no JUSO)
      security: [ { ApiKeyAuth: [] } ]
      parameters:
        - in: query
          name: full
          required: true
          schema: { type: string }
          description: "예: '서울특별시 종로구 청운동'"
        - in: query
          name: bunji
          required: true
          schema: { type: string }
          description: "예: '24-5' (부번 없으면 '24')"
        - in: query
          name: mtYn
          required: false
          schema: { type: string, pattern: "^[01]$" }
          description: "0=대지, 1=산 (기본 0)"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/BuildingBundle' }
