openapi: 3.1.0
info:
  title: RealEstate Aggregator (Building only)
  version: "1.1.0"
servers:
  - url: https://250812.vercel.app
paths:
  /realestate/building/by-pnu/{pnu}:
    get:
      summary: Get building register (title) by PNU
      operationId: getBuildingByPnu
      parameters:
        - in: path
          name: pnu
          required: true
          schema: { type: string, pattern: "^[0-9]{19}$" }
        - in: header
          name: X-API-Key
          required: false
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pnu: { type: string }
                  building: { type: object }
                  lastUpdatedAt: { type: string, format: date-time }
