openapi: 3.1.0
info: { title: RealEstate Aggregator (Building only), version: "1.2.0" }
servers: [ { url: https://250812.vercel.app } ]
paths:
  /realestate/building/by-pnu/{pnu}:
    get:
      summary: 건축물대장 표제부 조회
      parameters:
        - in: path
          name: pnu
          required: true
          schema: { type: string, pattern: "^[0-9]{19}$" }
        - in: header
          name: X-API-Key
          required: false
          schema: { type: string }
      responses:
        "200":
          description: OK
